config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users, :controllers  => { :registrations => 'registration/registrations' }
  
  resources :bikes

  resources :rides

  resources :purchase_transactions

  resources :users, only: [:index, :show, :edit, :update]

  resources :vendors
end

app/views/layouts/_navbar.html.erb
<header class="navbar justify-center">
  <div class="w-4/5 max-w-4xl flex items-center">
    <% if user_signed_in? %>
      <div class="navbar__brand">
        <%= link_to "/" do %>
          <p>Veloholic <span role="img">🚴</span></p>
        <% end %>
      </div>
      <div class="navbar__name">
        <p><span role="img">👨🏻‍💻</span> <%= current_user.username %></p>
      </div>
      <%= button_to "Sign out",
        destroy_user_session_path,
        method: :delete,
        class: "btn btn--dark" %>
    <% else %>
      <div class="navbar__brand">
        <%= link_to "/" do %>
          <p>Veloholic <span role="img">🚴</span></p>
        <% end %>
      </div>
      <div class="navbar__name">
        <%= link_to "Sign in",
          new_user_session_path,
          class: "btn btn--dark navbar__right" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside class="sidebar">
  <ul class="sidebar__menu">
    <li>
      <span role="img">🙋🏻‍♂️</span>
    </li>
    <li>
      <strong><%= current_user.username %></strong>
    </li>
    <li>
      <%= link_to "Home", root_path, class: "btn btn--light" %>
    </li>
    <li>
      <%= link_to "Bikes", bikes_path, class: "btn btn--light" %>
    </li>
    <li>
      <%= link_to "Rides", rides_path, class: "btn btn--light" %>
    </li>
    <li>
      <%= link_to "Vendors", vendors_path, class: "btn btn--light" %>
    </li>
    <li>
      <%= link_to "Purchase transaction", purchase_transactions_path, class: "btn btn--light" %>
    </li>
    <li>
      <%= link_to "Profile", users_path, class: "btn btn--light" %>
    </li>
  </ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veloholic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% flash.each do |key, value| %>
      <div class="w-100 flex justify-center">
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      </div>
    <% end %>
    <div class="flex justify-center">
      <div class="w-4/5 max-w-4xl flex">
        <% if user_signed_in? %>
            <%= render "layouts/sidebar" %>
          <% end %>
        <div class="application__container flex-col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>